package org.contextmapper.sample.tlas.infrastructure.api;

import org.contextmapper.sample.tlas.application.TlaApplicationService;
import org.contextmapper.sample.tlas.infrastructure.api.mapper.TlaApiDTOMapper;
import org.contextmapper.sample.tlas.infrastructure.api.model.TLADto;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

import static org.contextmapper.sample.tlas.infrastructure.api.mapper.TlaApiDTOMapper.tlaToDto;

/**
 * This is the actual implementation of the TlasApiController.
 * <p>
 * Note: Controller and DTOs are generated by the Open API generator.
 * You find the generated sources under 'target/generated-sources/openapi/src/main/java'.
 * To re-generate, call the Maven build: ./mvnw clean verify
 */
@Component
public class TlaApiDelegateImpl implements TlasApiDelegate {

    private TlaApplicationService applicationService;

    public TlaApiDelegateImpl(final TlaApplicationService applicationService) {
        this.applicationService = applicationService;
    }

    @Override
    public ResponseEntity<List<TLADto>> listTLAs() {
        return ResponseEntity.ok(applicationService.findAllTLAs().stream()
                .map(TlaApiDTOMapper::tlaToDto)
                .collect(Collectors.toList()));
    }

    @Override
    public ResponseEntity<TLADto> getTLAByName(final String name) {
        return ResponseEntity.ok(tlaToDto(applicationService.getTLAByName(name)));
    }
}
