openapi: "3.0.3"
info:
  title: Domain-driven Design & Context Mapper - Three Letter Abbreviations (TLAs) Sample Application
  description: |-
    This is an example application illustrating a DDD Bounded Context implementation based on Java and Spring Boot.
    It illustrates how to integrate Context Mapper to validate code against the CML domain model and using generated
    artifacts in the Arc42 documentation.
  contact:
    email: stefan@contextmapper.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://localhost:8080/api/v1
paths:
  /tlas:
    get:
      summary: List all TLAs
      operationId: listTLAs
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TLADto'
components:
  schemas:
    TLADto:
      type: object
      required:
        - name
        - meaning
      properties:
        name:
          type: string
          example: TLA
        meaning:
          type: string
          example: Three Letter Abbreviation
        alternativeMeanings:
          type: array
          example: Three Letter Acronym
          items:
            type: string
