@startuml

skinparam componentStyle uml2

"UC01_Resolve_TLA" as (UC01_Resolve_TLA)
"UC02_Propose_New_TLA" as (UC02_Propose_New_TLA)
"UC03_Accept_Proposed_TLA" as (UC03_Accept_Proposed_TLA)
"UC04_Archive_TLA" as (UC04_Archive_TLA)
"UC05_Propose_Alternative_Meaning_For_TLA" as (UC05_Propose_Alternative_Meaning_For_TLA)
"UC06_Report_Mistake" as (UC06_Report_Mistake)

"TLA User" as Actor_0
"TLA Manager" as Actor_1

left to right direction
Actor_0 -- UC01_Resolve_TLA
Actor_0 -- UC02_Propose_New_TLA
Actor_0 -- UC05_Propose_Alternative_Meaning_For_TLA
Actor_0 -- UC06_Report_Mistake
Actor_1 -- UC03_Accept_Proposed_TLA
Actor_1 -- UC04_Archive_TLA



@enduml
