apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backendServiceName }}
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 1044
      name: debug
      targetPort: 1044
  selector:
    app: {{ .Values.backendDeploymentName }}
