{{- if eq "local" $.Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendSecretsName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: aGVsbG8tdGxh

# local PW: hello-tla
{{- end }}