apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.dbStatefulSetName }}
  ports:
    - name: "5435"
      port: 5432
      targetPort: 5432
